# Generated by Django 4.1.2 on 2022-10-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='size')),
                ('fileName', models.TextField()),
                ('user', models.TextField()),
                ('extention', models.CharField(max_length=20, verbose_name='extention')),
                ('createdDate', models.CharField(max_length=20, verbose_name='createdDate')),
                ('modifiedDate', models.CharField(max_length=20, verbose_name='modifiedDate')),
                ('upFolder', models.TextField()),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
